---
- hosts: web 
  vars:
     hostname: "{{ lookup('file', '/home/ec2-user/hostname.txt') }}" 
  tasks:
   - name: Find serverindex.xml files in the folder
     find:
       paths: /
       patterns: "soppi"
       recurse: yes
     register: result
     become: yes
   - debug: 
       msg: output= "{{ result }}"
 # - debug: msg="{{ result }}"
   - name: copy
     shell: echo {{ result }} >/home/ec2-user/kk
   - name: changing hostnames
     replace:
       path: "{{ item.path }}"
       regexp: 'hello'
       replace: '{{ hostname }}'
       backup: yes
     become: yes
     with_items: "{{ result.files }}"


