---
- hosts: web
  tasks:
   - name: upgrade all packages, excluding kernel & foo related packages
     yum:
       name: '*'
       state: latest
       exclude: kernel*,foo*
     register: result
     become: yes
   - debug:
       msg: Output= {{ result }}
   - name: copy
     shell: echo {{ result.results }} >/home/ec2-user/output.txt

