---
- hosts: 172.31.35.190
  vars_prompt:
   - name: hostname
     prompt: "enter hostname"
     private: no 
  tasks:
   - name: changing hostnames
     lineinfile:
       dest: /etc/hostname
       regexp: 'ram'
       line: '{{hostname}}'
       state: present
     become: yes
   - name: reboot host
     shell: /sbin/shutdown -r now
     become: true
   - name: waiting for server booting up
     local_action: wait_for
     args:
       host: ''
       port: 22
       delay: 30
       timeout: 300
       state: started
     become: true


